// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXKuaReOV4d6qhK3Z80YgEkqL-M4KJwlw',
    appId: '1:973315235020:web:f60d938dd3cddc16ecb669',
    messagingSenderId: '973315235020',
    projectId: 'chatapp-20728',
    authDomain: 'chatapp-20728.firebaseapp.com',
    storageBucket: 'chatapp-20728.appspot.com',
    measurementId: 'G-ZWNPTN7JB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRmsSFbaq_-BkpqJj8kmnH9OF8S50Bx10',
    appId: '1:973315235020:android:41bf9f6cc73c375fecb669',
    messagingSenderId: '973315235020',
    projectId: 'chatapp-20728',
    storageBucket: 'chatapp-20728.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrEL8uhKJ2W1JTvCK6acJKrzCL06YP1ds',
    appId: '1:973315235020:ios:df04ae25284bfd7fecb669',
    messagingSenderId: '973315235020',
    projectId: 'chatapp-20728',
    storageBucket: 'chatapp-20728.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrEL8uhKJ2W1JTvCK6acJKrzCL06YP1ds',
    appId: '1:973315235020:ios:f7b93fb585e719a7ecb669',
    messagingSenderId: '973315235020',
    projectId: 'chatapp-20728',
    storageBucket: 'chatapp-20728.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
